const ENV = {
  TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID ?? "",
  TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET ?? "",
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID ?? "",
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET ?? "",
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET ?? "",
  NEXTAUTH_URL: process.env.NEXTAUTH_URL ?? "",
  NODE_ENV: process.env.NODE_ENV ?? "",
  // wallet factory addresses
  SEPOLIA_WALLET_FACTORY_ADDRESS:
    process.env.SEPOLIA_WALLET_FACTORY_ADDRESS ?? "0x9e0A2Ec943b48E5539cb3730e0E3fc27c8FB49A5",
  MUMBAI_WALLET_FACTORY_ADDRESS:
    process.env.MUMBAI_WALLET_FACTORY_ADDRESS ?? "0xB86b4A177003f38B97FecaFD6a087f90d350dC4c",
  OPTIMISM_GOERLI_WALLET_FACTORY_ADDRESS: process.env.OPTIMISM_GOERLI_WALLET_FACTORY_ADDRESS ?? "",
  AVALANCHE_FUJI_FACTORY_ADDRESS: process.env.AVALANCHE_FUJI_FACTORY_ADDRESS ?? "",
};

export default ENV;
